title: Design by Caitlyn
email: test@test.com
author: Caitlyn Sampica
description: A portfolio of art and design by Caitlyn Sampica

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

minima:
  skin: dark

header_pages:
  - about.md