title: Caitlyn Sampica
author:
  name: Caitlyn Sampica
  email: "test@test.com"

description: >
  Caitlyn Sampica's art and design portfolio

plugins:
  - jekyll-feed
  - jekyll-remote-theme

theme: minima

minima:
  skin: auto
  header_pages:
    - about.md