title: Caitlyn Sampica
email: test@test.com
author: Caitlyn Sampica
description: Caitlyn Sampica's art and design portfolio

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

minima:
  skin: auto

header_pages:
  - about.md