title: Caitlyn Sampica
author:
  name: Caitlyn Sampica
  email: "test@test.com"

description: >
  Caitlyn Sampica's art and design portfolio

theme: minima

minima:
  skin: auto
  header_pages:
    - about.md