title: Caitlyn Sampica
email: test@test.com
author:
  name: Caitlyn Sampica
description: Caitlyn Sampica's art and design portfolio

remote_theme: jekyll/minima@3cdd14d

plugins:
  - jekyll-remote-theme

minima:
  skin: auto
  header_pages:
    - about.md