name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile --tag kt-craft:$(date +%s)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: user/app:latest
