name: Build and Deploy App

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: jamessampica/thestudio:latest
    - name: Az CLI login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Deploy app
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az stack group create \
            --name the-studio \
            --resource-group the-studio-rg \
            --template-file iac/main.bicep \
            --deny-settings-mode 'none' \
            --parameters \
                dockerHubUsername=${{ secrets.DOCKERHUB_USERNAME }} \
                dockerHubToken=${{ secrets.DOCKERHUB_TOKEN }}

